# Generated by Django 5.0.2 on 2024-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('game', models.CharField(max_length=250)),
                ('date', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
