# Generated by Django 5.0.6 on 2024-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
