# Generated by Django 5.0.2 on 2024-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data_age_data_email_data_img_data_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
