# Generated by Django 5.0.2 on 2024-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
