# Generated by Django 5.0.2 on 2024-07-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_data_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img',
        ),
        migrations.RemoveField(
            model_name='data',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='data',
            name='place',
        ),
    ]
