# Generated by Django 5.0.2 on 2024-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='list',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
