# Generated by Django 5.0.2 on 2024-07-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_list_img_alter_list_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='img',
        ),
    ]
