# Generated by Django 5.0.2 on 2024-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_list_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(auto_created='media/', default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
