# Generated by Django 5.0.2 on 2024-07-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='DataItem',
        ),
    ]
