# Generated by Django 5.0.2 on 2024-03-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customise', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_status', models.IntegerField(choices=[(1, 'download'), (3, 'error'), (2, 'history')], default=0)),
                ('delete_status', models.IntegerField(choices=[(1, ';live'), (0, 'delete')], default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='customise.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Downloaded_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('games', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_history', to='games.games')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_items', to='downloads.history')),
            ],
        ),
    ]
